services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        PUBLIC_WHATSAPP_NUMBER: ${PUBLIC_WHATSAPP_NUMBER}
    ports:
      - "80:80"
    restart: unless-stopped
